#!/bin/sh
# Rebuild tagger_kernels.wasm and src/tagger-kernels.wasm.mjs (base64 embed).
# Needs an LLVM clang with the wasm32 target and wasm-ld (e.g. the one that
# ships with emscripten: /opt/homebrew/opt/emscripten/libexec/llvm/bin).
set -e
cd "$(dirname "$0")"
LLVM=${LLVM:-/opt/homebrew/opt/emscripten/libexec/llvm/bin}
"$LLVM/clang" --target=wasm32 -O3 -msimd128 -ffp-contract=off -nostdlib \
  -Wl,--no-entry -Wl,--import-memory -Wl,--strip-all \
  -o tagger_kernels.wasm tagger_kernels.c
node -e "const b=require('fs').readFileSync('tagger_kernels.wasm');require('fs').writeFileSync('../src/tagger-kernels.wasm.mjs','// generated by kernels/build.sh from kernels/tagger_kernels.c\nexport default \''+b.toString('base64')+'\';\n')"
ls -la tagger_kernels.wasm
