#!/usr/bin/env python3
"""Generate src/conduit_ctype_tables.h from a raw macOS libc dump.

Input: output of `dump_ctype --raw` compiled and run natively on macOS
(the platform whose libespeak-ng we must match bit for bit).  Only the
wide functions are used: the dump proves that on macOS the narrow
functions are identical to the wide ones for c >= -1 and return 0 /
identity for -128..-2 (checked again here).
"""
import sys
from collections import defaultdict

BOOL_FUNCS = ["iswalpha", "iswdigit", "iswspace", "iswupper", "iswlower", "iswpunct", "iswalnum"]
MAP_FUNCS = ["towlower", "towupper"]
NARROW = {"isalpha": "iswalpha", "isdigit": "iswdigit", "isspace": "iswspace", "isupper": "iswupper",
          "islower": "iswlower", "ispunct": "iswpunct", "isalnum": "iswalnum",
          "tolower": "towlower", "toupper": "towupper"}
WIDE_MAX = 0x1FFFFF


def main(src, dst):
    runs = defaultdict(list)
    for line in open(src, encoding="ascii"):
        name, a, b, v = line.split()
        runs[name].append((int(a), int(b), int(v)))

    # consistency checks on the dump itself
    for name, rr in runs.items():
        lo = -128 if name in NARROW else -1
        assert rr[0][0] == lo, (name, rr[0])
        assert rr[-1][1] == WIDE_MAX, (name, rr[-1])
        for (a0, b0, _), (a1, _, _) in zip(rr, rr[1:]):
            assert a1 == b0 + 1, name
    for narrow, wide in NARROW.items():
        n = runs[narrow]
        # first narrow run starts at -128 and must cover -128..-1 with value 0 (bool) or delta 0 (map)
        assert n[0][2] == 0 and n[0][1] >= -1, (narrow, n[0])
        assert [(max(a, -1), b, v) for a, b, v in n] == runs[wide], f"{narrow} != {wide} for c >= -1"

    out = []
    out.append("/* GENERATED by tools/wctype/gen_ctype_tables.py from a macOS libc dump. DO NOT EDIT. */")
    out.append("/* Reproduces macOS libc (C.UTF-8 locale) character classification for c in [-1, 0x1FFFFF]. */")
    out.append("#include <stdint.h>")
    for name in BOOL_FUNCS:
        rr = runs[name]
        assert rr[0][2] == 0
        toggles = []
        cur = 0
        for a, b, v in rr:
            assert v in (0, 1), (name, v)
            if v != cur:
                toggles.append(a)
                cur = v
        out.append(f"static const int32_t tbl_{name}[{len(toggles)}] = {{")
        for i in range(0, len(toggles), 12):
            out.append("  " + ", ".join(str(x) for x in toggles[i:i + 12]) + ",")
        out.append("};")
    for name in MAP_FUNCS:
        rr = runs[name]
        starts, deltas = [], []
        for a, b, v in rr:
            if deltas and deltas[-1] == v:
                continue
            starts.append(a)
            deltas.append(v)
        out.append(f"static const int32_t tbl_{name}_start[{len(starts)}] = {{")
        for i in range(0, len(starts), 12):
            out.append("  " + ", ".join(str(x) for x in starts[i:i + 12]) + ",")
        out.append("};")
        out.append(f"static const int32_t tbl_{name}_delta[{len(deltas)}] = {{")
        for i in range(0, len(deltas), 12):
            out.append("  " + ", ".join(str(x) for x in deltas[i:i + 12]) + ",")
        out.append("};")
    with open(dst, "w", encoding="ascii") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
